version: '3.3'
services:
  notifications:
    image: "notifications"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8080
      #- 8091:8091
    environment:
      APP_NET_BROKER_URI: "activemq:tcp://activemq1:61616"
  