apiVersion: v1
kind: Service
metadata:
  name: ms-container
  labels:
    app: ms-container
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ms-container
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-container
spec:
  selector:
    matchLabels:
      app: ms-container
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-container
    spec:
      containers:
        - name: ms-container
          image: xxxx.azurecr.io/ms-container:latest
          resources:
            limits:
              cpu: 150m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 10Mi
          livenessProbe:
             httpGet:
               path: /health
               port: 8080
             initialDelaySeconds: 50
             periodSeconds: 10
             timeoutSeconds: 10
             successThreshold: 1
             failureThreshold: 3
          readinessProbe:
             httpGet:
               path: /health
               port: 8080
             initialDelaySeconds: 50
             periodSeconds: 10
             timeoutSeconds: 10
             successThreshold: 1
             failureThreshold: 3
          ports:
            - containerPort: 8080
