version: '3.3'
services:
  db:
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: appdb
        MYSQL_USER: demouser
        MYSQL_PASSWORD: demopwd
  cache:
    image: redis:4-alpine
    command: sh -c 'echo "requirepass password" | redis-server -'
    ports:
      - 6379:6379
  customers:
    image: "customers"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
      #- 8091:8091
  