apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lpsa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lpsa
    spec:
      containers:
      - name: lpsa
        image: mzegarra/lpsa:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lpsa
  labels:
    app: lpsa
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http-traffic
  selector:
    app: lpsa
  type: LoadBalancer
